server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

spring:
  cloud:
    gateway:
      routes:
        - id: timesheet-service
          uri: lb://timesheet-service
          predicates:
            - Path=/testTimeSheet/**

        - id: summary-service
          uri: lb://summary-service
          predicates:
            - Path=/testSummary/**