server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: timesheet-service
          uri: lb://timesheet-service
          predicates:
            - Path=/testTimeSheet/**

        - id: timesheet-service
          uri: lb://timesheet-service
          predicates:
            - Path=/timeSheet/**

        - id: summary-service
          uri: lb://summary-service
          predicates:
            - Path=/AllSummary/**

        - id: summary-service
          uri: lb://summary-service
          predicates:
            - Path=/testSummary/**
